# Generated by Django 4.2.9 on 2026-02-19 15:54

import apps.bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dispute_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hauler_marked_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_pin',
            field=models.CharField(default=apps.bookings.models._generate_pickup_pin, max_length=6),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending_completion', 'Pending Completion'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('resolved_hauler', 'Resolved — Hauler'), ('resolved_client', 'Resolved — Client'), ('cancelled', 'Cancelled')], default='assigned', max_length=20),
        ),
    ]
