# Generated by Django 4.2.9 on 2026-02-19 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_booking_dispute_opened_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=10)),
                ('photo', models.ImageField(upload_to='evidence/%Y/%m/')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('captured_at', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='bookings.booking')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['captured_at'],
            },
        ),
    ]
