# Generated by Django 4.2.9 on 2026-02-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_city_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='haulerprofile',
            name='abandonment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='haulerprofile',
            name='no_show_count',
            field=models.IntegerField(default=0),
        ),
    ]
