# Generated by Django 4.2.9 on 2026-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_haulerprofile_abandonment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('warned', 'Warned'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='cancellation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_tier',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('phone_verified', 'Phone Verified'), ('id_verified', 'ID Verified')], default='unverified', max_length=20),
        ),
    ]
