# Generated by Django 4.2.9 on 2026-02-18 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('furniture_moving', 'Furniture Moving'), ('junk_removal', 'Junk Removal'), ('appliance', 'Appliance Install/Removal'), ('assembly', 'Assembly (IKEA etc.)'), ('heavy_lifting', 'Heavy Lifting / Loading'), ('packing', 'Packing / Unpacking'), ('storage', 'Storage Help'), ('other', 'Other')], max_length=30)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_address', models.CharField(max_length=500)),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposal_message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
