# Generated by Django 4.2.9 on 2026-02-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location_address',
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='job',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
