# Generated by Django 4.2.9 on 2026-02-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_chatroom_application_alter_chatroom_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending_completion', 'Pending Completion'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
