# Generated by Django 4.2.9 on 2026-02-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('jobs', '0004_chatroom_application_alter_chatroom_booking'),
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='jobs.jobapplication'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='bookings.booking'),
        ),
    ]
