# Generated by Django 4.2.9 on 2026-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_application_alter_chatroom_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
