# Generated by Django 4.2.9 on 2026-02-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('escrow_lock', 'Escrow Lock'), ('escrow_release', 'Escrow Release'), ('escrow_refund', 'Escrow Refund'), ('withdrawal', 'Withdrawal')], max_length=20),
        ),
    ]
