# Generated by Django 4.2.9 on 2026-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='available_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_processed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='reserve_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('escrow_lock', 'Escrow Lock'), ('escrow_release', 'Escrow Release'), ('escrow_refund', 'Escrow Refund'), ('reserve_hold', 'Reserve Hold'), ('reserve_release', 'Reserve Release'), ('withdrawal', 'Withdrawal')], max_length=20),
        ),
    ]
